#pragma once

#include <functional>
#include <thread>
#include <utility>

#include <storm/exception.h>
#include <storm/gpu_context.h>
#include <storm/ogl/api_functions_ogl.h>

namespace storm {

class GpuContextOgl;

class WeakGpuContextOgl {
public:
    explicit WeakGpuContextOgl(
            const std::shared_ptr<GpuContextOgl> &context ) :
        _context( context )
    {
    }

    std::shared_ptr<GpuContextOgl> tryLock() const {
        return _context.lock();
    }

    std::shared_ptr<GpuContextOgl> locked() const {
        if( const std::shared_ptr<GpuContextOgl> result = _context.lock() ) {
            return result;
        }

        throw Exception() <<
            "An associated GpuContext instance is destroyed";
    }

private:
    std::weak_ptr<GpuContextOgl> _context;
};

void setBooleanOpenGlState(
    const GpuContextOgl &gpuContext, GLenum state, bool value );

class GpuContextOgl : public GpuContext {
private:
    enum class CallType {
        Checked,
        Unchecked
    };

    template <class ApiFunction, CallType callType, class... Arguments>
    std::invoke_result_t<typename ApiFunction::Type, Arguments...>
    doCall( Arguments&&... arguments ) const {
        const ApiFunction& function = getFunction<ApiFunction>();

#ifndef NDEBUG
        if constexpr (callType == CallType::Checked) {
            assertThreadCompatibility();
        }

        if( !function.value ) {
            throw Exception() << ApiFunction::Name << " is not available";
        }
#endif

        activate();

        using ResultType =
            std::invoke_result_t<typename ApiFunction::Type, Arguments...>;

        if constexpr( std::is_same_v<ResultType, void> ) {
            std::invoke(
                function.value, std::forward<Arguments>(arguments)... );

            if constexpr (callType == CallType::Checked) {
                checkFunctionCall( ApiFunction::Name );
            }
        } else {
            const ResultType result = std::invoke(
                function.value, std::forward<Arguments>(arguments)... );

            if constexpr (callType == CallType::Checked) {
                checkFunctionCall( ApiFunction::Name );
            }

            return result;
        }
    }

public:
    using Pointer = std::shared_ptr<GpuContextOgl>;

    using ApiVersion = std::pair<unsigned, unsigned>;

    struct ExtensionSupportStatus {
        bool arbBufferStorage;
        bool arbGetProgramBinary;
        bool arbInvalidateSubdata;
        bool arbMultiBind;
        bool arbSeparateShaderObjects;
        bool arbTextureStorage;
        bool arbTextureStorageMultisample;
        bool arbTimerQuery;
        bool extTextureFilterAnisotropic;
        bool khrDebug;

        bool wglExtSwapControl;
        bool wglExtSwapControlTear;
    };

    // A derived class destructor is responsible for context deactivation
    GpuContextOgl();

    const ApiVersion& getApiVersion() const {
        return _apiVersion;
    }

    const ExtensionSupportStatus& getExtensionSupportStatus() const {
        return _extensionSupportStatus;
    }

    template <class ApiFunction>
    bool isFunctionAvailable() const {
        return getFunction<ApiFunction>().value;
    }

    template <class ApiFunction, class... Arguments>
    std::invoke_result_t<typename ApiFunction::Type, Arguments...>
    call( Arguments&&... arguments ) const {
        return doCall<ApiFunction, CallType::Checked>(
            std::forward<Arguments>(arguments)... );
    }

    template <class ApiFunction, class... Arguments>
    std::invoke_result_t<typename ApiFunction::Type, Arguments...>
    callUnchecked( Arguments&&... arguments ) const {
        return doCall<ApiFunction, CallType::Unchecked>(
            std::forward<Arguments>(arguments)... );
    }

protected:
    void loadApiFunctions(
        const std::function<void*(std::string_view)> &loader );

    void assertThreadCompatibility() const {
#ifndef NDEBUG
        if( _threadId != std::this_thread::get_id() ) {
            throw Exception() <<
                "A 'GpuContext' instance doesn't belong to this thread";
        }
#endif
    }

    virtual void activate() const = 0;

private:
    template <class ApiFunction>
    const ApiFunction& getFunction() const;

    void checkFunctionCall( std::string_view functionName ) const {
#ifndef NDEBUG
        if( callUnchecked<GlGetError>() != GL_NO_ERROR ) {
            throw Exception() << functionName << " has failed";
        }
#else
        (void)functionName;
#endif
    }

    void obtainApiVersion();
    void obtainExtensionSupportStatus();

    std::thread::id _threadId;

    ApiVersion _apiVersion;
    ExtensionSupportStatus _extensionSupportStatus = {};

    GlCullFace
        _glCullFace;
    GlFrontFace
        _glFrontFace;
    GlHint
        _glHint;
    GlLineWidth
        _glLineWidth;
    GlPointSize
        _glPointSize;
    GlPolygonMode
        _glPolygonMode;
    GlScissor
        _glScissor;
    GlTexParameterf
        _glTexParameterf;
    GlTexParameterfv
        _glTexParameterfv;
    GlTexParameteri
        _glTexParameteri;
    GlTexParameteriv
        _glTexParameteriv;
    GlTexImage1D
        _glTexImage1D;
    GlTexImage2D
        _glTexImage2D;
    GlDrawBuffer
        _glDrawBuffer;
    GlClear
        _glClear;
    GlClearColor
        _glClearColor;
    GlClearStencil
        _glClearStencil;
    GlClearDepth
        _glClearDepth;
    GlStencilMask
        _glStencilMask;
    GlColorMask
        _glColorMask;
    GlDepthMask
        _glDepthMask;
    GlDisable
        _glDisable;
    GlEnable
        _glEnable;
    GlFinish
        _glFinish;
    GlFlush
        _glFlush;
    GlBlendFunc
        _glBlendFunc;
    GlLogicOp
        _glLogicOp;
    GlStencilFunc
        _glStencilFunc;
    GlStencilOp
        _glStencilOp;
    GlDepthFunc
        _glDepthFunc;
    GlPixelStoref
        _glPixelStoref;
    GlPixelStorei
        _glPixelStorei;
    GlReadBuffer
        _glReadBuffer;
    GlReadPixels
        _glReadPixels;
    GlGetBooleanv
        _glGetBooleanv;
    GlGetDoublev
        _glGetDoublev;
    GlGetError
        _glGetError;
    GlGetFloatv
        _glGetFloatv;
    GlGetIntegerv
        _glGetIntegerv;
    GlGetString
        _glGetString;
    GlGetTexImage
        _glGetTexImage;
    GlGetTexParameterfv
        _glGetTexParameterfv;
    GlGetTexParameteriv
        _glGetTexParameteriv;
    GlGetTexLevelParameterfv
        _glGetTexLevelParameterfv;
    GlGetTexLevelParameteriv
        _glGetTexLevelParameteriv;
    GlIsEnabled
        _glIsEnabled;
    GlDepthRange
        _glDepthRange;
    GlViewport
        _glViewport;
    GlDrawArrays
        _glDrawArrays;
    GlDrawElements
        _glDrawElements;
    GlGetPointerv
        _glGetPointerv;
    GlPolygonOffset
        _glPolygonOffset;
    GlCopyTexImage1D
        _glCopyTexImage1D;
    GlCopyTexImage2D
        _glCopyTexImage2D;
    GlCopyTexSubImage1D
        _glCopyTexSubImage1D;
    GlCopyTexSubImage2D
        _glCopyTexSubImage2D;
    GlTexSubImage1D
        _glTexSubImage1D;
    GlTexSubImage2D
        _glTexSubImage2D;
    GlBindTexture
        _glBindTexture;
    GlDeleteTextures
        _glDeleteTextures;
    GlGenTextures
        _glGenTextures;
    GlIsTexture
        _glIsTexture;
    GlDrawRangeElements
        _glDrawRangeElements;
    GlTexImage3D
        _glTexImage3D;
    GlTexSubImage3D
        _glTexSubImage3D;
    GlCopyTexSubImage3D
        _glCopyTexSubImage3D;
    GlActiveTexture
        _glActiveTexture;
    GlSampleCoverage
        _glSampleCoverage;
    GlCompressedTexImage3D
        _glCompressedTexImage3D;
    GlCompressedTexImage2D
        _glCompressedTexImage2D;
    GlCompressedTexImage1D
        _glCompressedTexImage1D;
    GlCompressedTexSubImage3D
        _glCompressedTexSubImage3D;
    GlCompressedTexSubImage2D
        _glCompressedTexSubImage2D;
    GlCompressedTexSubImage1D
        _glCompressedTexSubImage1D;
    GlGetCompressedTexImage
        _glGetCompressedTexImage;
    GlBlendFuncSeparate
        _glBlendFuncSeparate;
    GlMultiDrawArrays
        _glMultiDrawArrays;
    GlMultiDrawElements
        _glMultiDrawElements;
    GlPointParameterf
        _glPointParameterf;
    GlPointParameterfv
        _glPointParameterfv;
    GlPointParameteri
        _glPointParameteri;
    GlPointParameteriv
        _glPointParameteriv;
    GlBlendColor
        _glBlendColor;
    GlBlendEquation
        _glBlendEquation;
    GlGenQueries
        _glGenQueries;
    GlDeleteQueries
        _glDeleteQueries;
    GlIsQuery
        _glIsQuery;
    GlBeginQuery
        _glBeginQuery;
    GlEndQuery
        _glEndQuery;
    GlGetQueryiv
        _glGetQueryiv;
    GlGetQueryObjectiv
        _glGetQueryObjectiv;
    GlGetQueryObjectuiv
        _glGetQueryObjectuiv;
    GlBindBuffer
        _glBindBuffer;
    GlDeleteBuffers
        _glDeleteBuffers;
    GlGenBuffers
        _glGenBuffers;
    GlIsBuffer
        _glIsBuffer;
    GlBufferData
        _glBufferData;
    GlBufferSubData
        _glBufferSubData;
    GlGetBufferSubData
        _glGetBufferSubData;
    GlMapBuffer
        _glMapBuffer;
    GlUnmapBuffer
        _glUnmapBuffer;
    GlGetBufferParameteriv
        _glGetBufferParameteriv;
    GlGetBufferPointerv
        _glGetBufferPointerv;
    GlBlendEquationSeparate
        _glBlendEquationSeparate;
    GlDrawBuffers
        _glDrawBuffers;
    GlStencilOpSeparate
        _glStencilOpSeparate;
    GlStencilFuncSeparate
        _glStencilFuncSeparate;
    GlStencilMaskSeparate
        _glStencilMaskSeparate;
    GlAttachShader
        _glAttachShader;
    GlBindAttribLocation
        _glBindAttribLocation;
    GlCompileShader
        _glCompileShader;
    GlCreateProgram
        _glCreateProgram;
    GlCreateShader
        _glCreateShader;
    GlDeleteProgram
        _glDeleteProgram;
    GlDeleteShader
        _glDeleteShader;
    GlDetachShader
        _glDetachShader;
    GlDisableVertexAttribArray
        _glDisableVertexAttribArray;
    GlEnableVertexAttribArray
        _glEnableVertexAttribArray;
    GlGetActiveAttrib
        _glGetActiveAttrib;
    GlGetActiveUniform
        _glGetActiveUniform;
    GlGetAttachedShaders
        _glGetAttachedShaders;
    GlGetAttribLocation
        _glGetAttribLocation;
    GlGetProgramiv
        _glGetProgramiv;
    GlGetProgramInfoLog
        _glGetProgramInfoLog;
    GlGetShaderiv
        _glGetShaderiv;
    GlGetShaderInfoLog
        _glGetShaderInfoLog;
    GlGetShaderSource
        _glGetShaderSource;
    GlGetUniformLocation
        _glGetUniformLocation;
    GlGetUniformfv
        _glGetUniformfv;
    GlGetUniformiv
        _glGetUniformiv;
    GlGetVertexAttribdv
        _glGetVertexAttribdv;
    GlGetVertexAttribfv
        _glGetVertexAttribfv;
    GlGetVertexAttribiv
        _glGetVertexAttribiv;
    GlGetVertexAttribPointerv
        _glGetVertexAttribPointerv;
    GlIsProgram
        _glIsProgram;
    GlIsShader
        _glIsShader;
    GlLinkProgram
        _glLinkProgram;
    GlShaderSource
        _glShaderSource;
    GlUseProgram
        _glUseProgram;
    GlUniform1f
        _glUniform1f;
    GlUniform2f
        _glUniform2f;
    GlUniform3f
        _glUniform3f;
    GlUniform4f
        _glUniform4f;
    GlUniform1i
        _glUniform1i;
    GlUniform2i
        _glUniform2i;
    GlUniform3i
        _glUniform3i;
    GlUniform4i
        _glUniform4i;
    GlUniform1fv
        _glUniform1fv;
    GlUniform2fv
        _glUniform2fv;
    GlUniform3fv
        _glUniform3fv;
    GlUniform4fv
        _glUniform4fv;
    GlUniform1iv
        _glUniform1iv;
    GlUniform2iv
        _glUniform2iv;
    GlUniform3iv
        _glUniform3iv;
    GlUniform4iv
        _glUniform4iv;
    GlUniformMatrix2fv
        _glUniformMatrix2fv;
    GlUniformMatrix3fv
        _glUniformMatrix3fv;
    GlUniformMatrix4fv
        _glUniformMatrix4fv;
    GlValidateProgram
        _glValidateProgram;
    GlVertexAttrib1d
        _glVertexAttrib1d;
    GlVertexAttrib1dv
        _glVertexAttrib1dv;
    GlVertexAttrib1f
        _glVertexAttrib1f;
    GlVertexAttrib1fv
        _glVertexAttrib1fv;
    GlVertexAttrib1s
        _glVertexAttrib1s;
    GlVertexAttrib1sv
        _glVertexAttrib1sv;
    GlVertexAttrib2d
        _glVertexAttrib2d;
    GlVertexAttrib2dv
        _glVertexAttrib2dv;
    GlVertexAttrib2f
        _glVertexAttrib2f;
    GlVertexAttrib2fv
        _glVertexAttrib2fv;
    GlVertexAttrib2s
        _glVertexAttrib2s;
    GlVertexAttrib2sv
        _glVertexAttrib2sv;
    GlVertexAttrib3d
        _glVertexAttrib3d;
    GlVertexAttrib3dv
        _glVertexAttrib3dv;
    GlVertexAttrib3f
        _glVertexAttrib3f;
    GlVertexAttrib3fv
        _glVertexAttrib3fv;
    GlVertexAttrib3s
        _glVertexAttrib3s;
    GlVertexAttrib3sv
        _glVertexAttrib3sv;
    GlVertexAttrib4Nbv
        _glVertexAttrib4Nbv;
    GlVertexAttrib4Niv
        _glVertexAttrib4Niv;
    GlVertexAttrib4Nsv
        _glVertexAttrib4Nsv;
    GlVertexAttrib4Nub
        _glVertexAttrib4Nub;
    GlVertexAttrib4Nubv
        _glVertexAttrib4Nubv;
    GlVertexAttrib4Nuiv
        _glVertexAttrib4Nuiv;
    GlVertexAttrib4Nusv
        _glVertexAttrib4Nusv;
    GlVertexAttrib4bv
        _glVertexAttrib4bv;
    GlVertexAttrib4d
        _glVertexAttrib4d;
    GlVertexAttrib4dv
        _glVertexAttrib4dv;
    GlVertexAttrib4f
        _glVertexAttrib4f;
    GlVertexAttrib4fv
        _glVertexAttrib4fv;
    GlVertexAttrib4iv
        _glVertexAttrib4iv;
    GlVertexAttrib4s
        _glVertexAttrib4s;
    GlVertexAttrib4sv
        _glVertexAttrib4sv;
    GlVertexAttrib4ubv
        _glVertexAttrib4ubv;
    GlVertexAttrib4uiv
        _glVertexAttrib4uiv;
    GlVertexAttrib4usv
        _glVertexAttrib4usv;
    GlVertexAttribPointer
        _glVertexAttribPointer;
    GlUniformMatrix2x3fv
        _glUniformMatrix2x3fv;
    GlUniformMatrix3x2fv
        _glUniformMatrix3x2fv;
    GlUniformMatrix2x4fv
        _glUniformMatrix2x4fv;
    GlUniformMatrix4x2fv
        _glUniformMatrix4x2fv;
    GlUniformMatrix3x4fv
        _glUniformMatrix3x4fv;
    GlUniformMatrix4x3fv
        _glUniformMatrix4x3fv;
    GlColorMaski
        _glColorMaski;
    GlGetBooleani_v
        _glGetBooleani_v;
    GlGetIntegeri_v
        _glGetIntegeri_v;
    GlEnablei
        _glEnablei;
    GlDisablei
        _glDisablei;
    GlIsEnabledi
        _glIsEnabledi;
    GlBeginTransformFeedback
        _glBeginTransformFeedback;
    GlEndTransformFeedback
        _glEndTransformFeedback;
    GlBindBufferRange
        _glBindBufferRange;
    GlBindBufferBase
        _glBindBufferBase;
    GlTransformFeedbackVaryings
        _glTransformFeedbackVaryings;
    GlGetTransformFeedbackVarying
        _glGetTransformFeedbackVarying;
    GlClampColor
        _glClampColor;
    GlBeginConditionalRender
        _glBeginConditionalRender;
    GlEndConditionalRender
        _glEndConditionalRender;
    GlVertexAttribIPointer
        _glVertexAttribIPointer;
    GlGetVertexAttribIiv
        _glGetVertexAttribIiv;
    GlGetVertexAttribIuiv
        _glGetVertexAttribIuiv;
    GlVertexAttribI1i
        _glVertexAttribI1i;
    GlVertexAttribI2i
        _glVertexAttribI2i;
    GlVertexAttribI3i
        _glVertexAttribI3i;
    GlVertexAttribI4i
        _glVertexAttribI4i;
    GlVertexAttribI1ui
        _glVertexAttribI1ui;
    GlVertexAttribI2ui
        _glVertexAttribI2ui;
    GlVertexAttribI3ui
        _glVertexAttribI3ui;
    GlVertexAttribI4ui
        _glVertexAttribI4ui;
    GlVertexAttribI1iv
        _glVertexAttribI1iv;
    GlVertexAttribI2iv
        _glVertexAttribI2iv;
    GlVertexAttribI3iv
        _glVertexAttribI3iv;
    GlVertexAttribI4iv
        _glVertexAttribI4iv;
    GlVertexAttribI1uiv
        _glVertexAttribI1uiv;
    GlVertexAttribI2uiv
        _glVertexAttribI2uiv;
    GlVertexAttribI3uiv
        _glVertexAttribI3uiv;
    GlVertexAttribI4uiv
        _glVertexAttribI4uiv;
    GlVertexAttribI4bv
        _glVertexAttribI4bv;
    GlVertexAttribI4sv
        _glVertexAttribI4sv;
    GlVertexAttribI4ubv
        _glVertexAttribI4ubv;
    GlVertexAttribI4usv
        _glVertexAttribI4usv;
    GlGetUniformuiv
        _glGetUniformuiv;
    GlBindFragDataLocation
        _glBindFragDataLocation;
    GlGetFragDataLocation
        _glGetFragDataLocation;
    GlUniform1ui
        _glUniform1ui;
    GlUniform2ui
        _glUniform2ui;
    GlUniform3ui
        _glUniform3ui;
    GlUniform4ui
        _glUniform4ui;
    GlUniform1uiv
        _glUniform1uiv;
    GlUniform2uiv
        _glUniform2uiv;
    GlUniform3uiv
        _glUniform3uiv;
    GlUniform4uiv
        _glUniform4uiv;
    GlTexParameterIiv
        _glTexParameterIiv;
    GlTexParameterIuiv
        _glTexParameterIuiv;
    GlGetTexParameterIiv
        _glGetTexParameterIiv;
    GlGetTexParameterIuiv
        _glGetTexParameterIuiv;
    GlClearBufferiv
        _glClearBufferiv;
    GlClearBufferuiv
        _glClearBufferuiv;
    GlClearBufferfv
        _glClearBufferfv;
    GlClearBufferfi
        _glClearBufferfi;
    GlGetStringi
        _glGetStringi;
    GlIsRenderbuffer
        _glIsRenderbuffer;
    GlBindRenderbuffer
        _glBindRenderbuffer;
    GlDeleteRenderbuffers
        _glDeleteRenderbuffers;
    GlGenRenderbuffers
        _glGenRenderbuffers;
    GlRenderbufferStorage
        _glRenderbufferStorage;
    GlGetRenderbufferParameteriv
        _glGetRenderbufferParameteriv;
    GlIsFramebuffer
        _glIsFramebuffer;
    GlBindFramebuffer
        _glBindFramebuffer;
    GlDeleteFramebuffers
        _glDeleteFramebuffers;
    GlGenFramebuffers
        _glGenFramebuffers;
    GlCheckFramebufferStatus
        _glCheckFramebufferStatus;
    GlFramebufferTexture1D
        _glFramebufferTexture1D;
    GlFramebufferTexture2D
        _glFramebufferTexture2D;
    GlFramebufferTexture3D
        _glFramebufferTexture3D;
    GlFramebufferRenderbuffer
        _glFramebufferRenderbuffer;
    GlGetFramebufferAttachmentParameteriv
        _glGetFramebufferAttachmentParameteriv;
    GlGenerateMipmap
        _glGenerateMipmap;
    GlBlitFramebuffer
        _glBlitFramebuffer;
    GlRenderbufferStorageMultisample
        _glRenderbufferStorageMultisample;
    GlFramebufferTextureLayer
        _glFramebufferTextureLayer;
    GlMapBufferRange
        _glMapBufferRange;
    GlFlushMappedBufferRange
        _glFlushMappedBufferRange;
    GlBindVertexArray
        _glBindVertexArray;
    GlDeleteVertexArrays
        _glDeleteVertexArrays;
    GlGenVertexArrays
        _glGenVertexArrays;
    GlIsVertexArray
        _glIsVertexArray;
    GlDrawArraysInstanced
        _glDrawArraysInstanced;
    GlDrawElementsInstanced
        _glDrawElementsInstanced;
    GlTexBuffer
        _glTexBuffer;
    GlPrimitiveRestartIndex
        _glPrimitiveRestartIndex;
    GlCopyBufferSubData
        _glCopyBufferSubData;
    GlGetUniformIndices
        _glGetUniformIndices;
    GlGetActiveUniformsiv
        _glGetActiveUniformsiv;
    GlGetActiveUniformName
        _glGetActiveUniformName;
    GlGetUniformBlockIndex
        _glGetUniformBlockIndex;
    GlGetActiveUniformBlockiv
        _glGetActiveUniformBlockiv;
    GlGetActiveUniformBlockName
        _glGetActiveUniformBlockName;
    GlUniformBlockBinding
        _glUniformBlockBinding;
    GlDrawElementsBaseVertex
        _glDrawElementsBaseVertex;
    GlDrawRangeElementsBaseVertex
        _glDrawRangeElementsBaseVertex;
    GlDrawElementsInstancedBaseVertex
        _glDrawElementsInstancedBaseVertex;
    GlMultiDrawElementsBaseVertex
        _glMultiDrawElementsBaseVertex;
    GlProvokingVertex
        _glProvokingVertex;
    GlFenceSync
        _glFenceSync;
    GlIsSync
        _glIsSync;
    GlDeleteSync
        _glDeleteSync;
    GlClientWaitSync
        _glClientWaitSync;
    GlWaitSync
        _glWaitSync;
    GlGetInteger64v
        _glGetInteger64v;
    GlGetSynciv
        _glGetSynciv;
    GlGetInteger64i_v
        _glGetInteger64i_v;
    GlGetBufferParameteri64v
        _glGetBufferParameteri64v;
    GlFramebufferTexture
        _glFramebufferTexture;
    GlTexImage2DMultisample
        _glTexImage2DMultisample;
    GlTexImage3DMultisample
        _glTexImage3DMultisample;
    GlGetMultisamplefv
        _glGetMultisamplefv;
    GlSampleMaski
        _glSampleMaski;
    GlBindFragDataLocationIndexed
        _glBindFragDataLocationIndexed;
    GlGetFragDataIndex
        _glGetFragDataIndex;
    GlGenSamplers
        _glGenSamplers;
    GlDeleteSamplers
        _glDeleteSamplers;
    GlIsSampler
        _glIsSampler;
    GlBindSampler
        _glBindSampler;
    GlSamplerParameteri
        _glSamplerParameteri;
    GlSamplerParameteriv
        _glSamplerParameteriv;
    GlSamplerParameterf
        _glSamplerParameterf;
    GlSamplerParameterfv
        _glSamplerParameterfv;
    GlSamplerParameterIiv
        _glSamplerParameterIiv;
    GlSamplerParameterIuiv
        _glSamplerParameterIuiv;
    GlGetSamplerParameteriv
        _glGetSamplerParameteriv;
    GlGetSamplerParameterIiv
        _glGetSamplerParameterIiv;
    GlGetSamplerParameterfv
        _glGetSamplerParameterfv;
    GlGetSamplerParameterIuiv
        _glGetSamplerParameterIuiv;
    GlQueryCounter
        _glQueryCounter;
    GlGetQueryObjecti64v
        _glGetQueryObjecti64v;
    GlGetQueryObjectui64v
        _glGetQueryObjectui64v;
    GlVertexAttribDivisor
        _glVertexAttribDivisor;
    GlVertexAttribP1ui
        _glVertexAttribP1ui;
    GlVertexAttribP1uiv
        _glVertexAttribP1uiv;
    GlVertexAttribP2ui
        _glVertexAttribP2ui;
    GlVertexAttribP2uiv
        _glVertexAttribP2uiv;
    GlVertexAttribP3ui
        _glVertexAttribP3ui;
    GlVertexAttribP3uiv
        _glVertexAttribP3uiv;
    GlVertexAttribP4ui
        _glVertexAttribP4ui;
    GlVertexAttribP4uiv
        _glVertexAttribP4uiv;
    GlMinSampleShading
        _glMinSampleShading;
    GlBlendEquationi
        _glBlendEquationi;
    GlBlendEquationSeparatei
        _glBlendEquationSeparatei;
    GlBlendFunci
        _glBlendFunci;
    GlBlendFuncSeparatei
        _glBlendFuncSeparatei;
    GlDrawArraysIndirect
        _glDrawArraysIndirect;
    GlDrawElementsIndirect
        _glDrawElementsIndirect;
    GlUniform1d
        _glUniform1d;
    GlUniform2d
        _glUniform2d;
    GlUniform3d
        _glUniform3d;
    GlUniform4d
        _glUniform4d;
    GlUniform1dv
        _glUniform1dv;
    GlUniform2dv
        _glUniform2dv;
    GlUniform3dv
        _glUniform3dv;
    GlUniform4dv
        _glUniform4dv;
    GlUniformMatrix2dv
        _glUniformMatrix2dv;
    GlUniformMatrix3dv
        _glUniformMatrix3dv;
    GlUniformMatrix4dv
        _glUniformMatrix4dv;
    GlUniformMatrix2x3dv
        _glUniformMatrix2x3dv;
    GlUniformMatrix2x4dv
        _glUniformMatrix2x4dv;
    GlUniformMatrix3x2dv
        _glUniformMatrix3x2dv;
    GlUniformMatrix3x4dv
        _glUniformMatrix3x4dv;
    GlUniformMatrix4x2dv
        _glUniformMatrix4x2dv;
    GlUniformMatrix4x3dv
        _glUniformMatrix4x3dv;
    GlGetUniformdv
        _glGetUniformdv;
    GlGetSubroutineUniformLocation
        _glGetSubroutineUniformLocation;
    GlGetSubroutineIndex
        _glGetSubroutineIndex;
    GlGetActiveSubroutineUniformiv
        _glGetActiveSubroutineUniformiv;
    GlGetActiveSubroutineUniformName
        _glGetActiveSubroutineUniformName;
    GlGetActiveSubroutineName
        _glGetActiveSubroutineName;
    GlUniformSubroutinesuiv
        _glUniformSubroutinesuiv;
    GlGetUniformSubroutineuiv
        _glGetUniformSubroutineuiv;
    GlGetProgramStageiv
        _glGetProgramStageiv;
    GlPatchParameteri
        _glPatchParameteri;
    GlPatchParameterfv
        _glPatchParameterfv;
    GlBindTransformFeedback
        _glBindTransformFeedback;
    GlDeleteTransformFeedbacks
        _glDeleteTransformFeedbacks;
    GlGenTransformFeedbacks
        _glGenTransformFeedbacks;
    GlIsTransformFeedback
        _glIsTransformFeedback;
    GlPauseTransformFeedback
        _glPauseTransformFeedback;
    GlResumeTransformFeedback
        _glResumeTransformFeedback;
    GlDrawTransformFeedback
        _glDrawTransformFeedback;
    GlDrawTransformFeedbackStream
        _glDrawTransformFeedbackStream;
    GlBeginQueryIndexed
        _glBeginQueryIndexed;
    GlEndQueryIndexed
        _glEndQueryIndexed;
    GlGetQueryIndexediv
        _glGetQueryIndexediv;
    GlReleaseShaderCompiler
        _glReleaseShaderCompiler;
    GlShaderBinary
        _glShaderBinary;
    GlGetShaderPrecisionFormat
        _glGetShaderPrecisionFormat;
    GlDepthRangef
        _glDepthRangef;
    GlClearDepthf
        _glClearDepthf;
    GlGetProgramBinary
        _glGetProgramBinary;
    GlProgramBinary
        _glProgramBinary;
    GlProgramParameteri
        _glProgramParameteri;
    GlUseProgramStages
        _glUseProgramStages;
    GlActiveShaderProgram
        _glActiveShaderProgram;
    GlCreateShaderProgramv
        _glCreateShaderProgramv;
    GlBindProgramPipeline
        _glBindProgramPipeline;
    GlDeleteProgramPipelines
        _glDeleteProgramPipelines;
    GlGenProgramPipelines
        _glGenProgramPipelines;
    GlIsProgramPipeline
        _glIsProgramPipeline;
    GlGetProgramPipelineiv
        _glGetProgramPipelineiv;
    GlProgramUniform1i
        _glProgramUniform1i;
    GlProgramUniform1iv
        _glProgramUniform1iv;
    GlProgramUniform1f
        _glProgramUniform1f;
    GlProgramUniform1fv
        _glProgramUniform1fv;
    GlProgramUniform1d
        _glProgramUniform1d;
    GlProgramUniform1dv
        _glProgramUniform1dv;
    GlProgramUniform1ui
        _glProgramUniform1ui;
    GlProgramUniform1uiv
        _glProgramUniform1uiv;
    GlProgramUniform2i
        _glProgramUniform2i;
    GlProgramUniform2iv
        _glProgramUniform2iv;
    GlProgramUniform2f
        _glProgramUniform2f;
    GlProgramUniform2fv
        _glProgramUniform2fv;
    GlProgramUniform2d
        _glProgramUniform2d;
    GlProgramUniform2dv
        _glProgramUniform2dv;
    GlProgramUniform2ui
        _glProgramUniform2ui;
    GlProgramUniform2uiv
        _glProgramUniform2uiv;
    GlProgramUniform3i
        _glProgramUniform3i;
    GlProgramUniform3iv
        _glProgramUniform3iv;
    GlProgramUniform3f
        _glProgramUniform3f;
    GlProgramUniform3fv
        _glProgramUniform3fv;
    GlProgramUniform3d
        _glProgramUniform3d;
    GlProgramUniform3dv
        _glProgramUniform3dv;
    GlProgramUniform3ui
        _glProgramUniform3ui;
    GlProgramUniform3uiv
        _glProgramUniform3uiv;
    GlProgramUniform4i
        _glProgramUniform4i;
    GlProgramUniform4iv
        _glProgramUniform4iv;
    GlProgramUniform4f
        _glProgramUniform4f;
    GlProgramUniform4fv
        _glProgramUniform4fv;
    GlProgramUniform4d
        _glProgramUniform4d;
    GlProgramUniform4dv
        _glProgramUniform4dv;
    GlProgramUniform4ui
        _glProgramUniform4ui;
    GlProgramUniform4uiv
        _glProgramUniform4uiv;
    GlProgramUniformMatrix2fv
        _glProgramUniformMatrix2fv;
    GlProgramUniformMatrix3fv
        _glProgramUniformMatrix3fv;
    GlProgramUniformMatrix4fv
        _glProgramUniformMatrix4fv;
    GlProgramUniformMatrix2dv
        _glProgramUniformMatrix2dv;
    GlProgramUniformMatrix3dv
        _glProgramUniformMatrix3dv;
    GlProgramUniformMatrix4dv
        _glProgramUniformMatrix4dv;
    GlProgramUniformMatrix2x3fv
        _glProgramUniformMatrix2x3fv;
    GlProgramUniformMatrix3x2fv
        _glProgramUniformMatrix3x2fv;
    GlProgramUniformMatrix2x4fv
        _glProgramUniformMatrix2x4fv;
    GlProgramUniformMatrix4x2fv
        _glProgramUniformMatrix4x2fv;
    GlProgramUniformMatrix3x4fv
        _glProgramUniformMatrix3x4fv;
    GlProgramUniformMatrix4x3fv
        _glProgramUniformMatrix4x3fv;
    GlProgramUniformMatrix2x3dv
        _glProgramUniformMatrix2x3dv;
    GlProgramUniformMatrix3x2dv
        _glProgramUniformMatrix3x2dv;
    GlProgramUniformMatrix2x4dv
        _glProgramUniformMatrix2x4dv;
    GlProgramUniformMatrix4x2dv
        _glProgramUniformMatrix4x2dv;
    GlProgramUniformMatrix3x4dv
        _glProgramUniformMatrix3x4dv;
    GlProgramUniformMatrix4x3dv
        _glProgramUniformMatrix4x3dv;
    GlValidateProgramPipeline
        _glValidateProgramPipeline;
    GlGetProgramPipelineInfoLog
        _glGetProgramPipelineInfoLog;
    GlVertexAttribL1d
        _glVertexAttribL1d;
    GlVertexAttribL2d
        _glVertexAttribL2d;
    GlVertexAttribL3d
        _glVertexAttribL3d;
    GlVertexAttribL4d
        _glVertexAttribL4d;
    GlVertexAttribL1dv
        _glVertexAttribL1dv;
    GlVertexAttribL2dv
        _glVertexAttribL2dv;
    GlVertexAttribL3dv
        _glVertexAttribL3dv;
    GlVertexAttribL4dv
        _glVertexAttribL4dv;
    GlVertexAttribLPointer
        _glVertexAttribLPointer;
    GlGetVertexAttribLdv
        _glGetVertexAttribLdv;
    GlViewportArrayv
        _glViewportArrayv;
    GlViewportIndexedf
        _glViewportIndexedf;
    GlViewportIndexedfv
        _glViewportIndexedfv;
    GlScissorArrayv
        _glScissorArrayv;
    GlScissorIndexed
        _glScissorIndexed;
    GlScissorIndexedv
        _glScissorIndexedv;
    GlDepthRangeArrayv
        _glDepthRangeArrayv;
    GlDepthRangeIndexed
        _glDepthRangeIndexed;
    GlGetFloati_v
        _glGetFloati_v;
    GlGetDoublei_v
        _glGetDoublei_v;
    GlDrawArraysInstancedBaseInstance
        _glDrawArraysInstancedBaseInstance;
    GlDrawElementsInstancedBaseInstance
        _glDrawElementsInstancedBaseInstance;
    GlDrawElementsInstancedBaseVertexBaseInstance
        _glDrawElementsInstancedBaseVertexBaseInstance;
    GlGetInternalformativ
        _glGetInternalformativ;
    GlGetActiveAtomicCounterBufferiv
        _glGetActiveAtomicCounterBufferiv;
    GlBindImageTexture
        _glBindImageTexture;
    GlMemoryBarrier
        _glMemoryBarrier;
    GlTexStorage1D
        _glTexStorage1D;
    GlTexStorage2D
        _glTexStorage2D;
    GlTexStorage3D
        _glTexStorage3D;
    GlDrawTransformFeedbackInstanced
        _glDrawTransformFeedbackInstanced;
    GlDrawTransformFeedbackStreamInstanced
        _glDrawTransformFeedbackStreamInstanced;
    GlClearBufferData
        _glClearBufferData;
    GlClearBufferSubData
        _glClearBufferSubData;
    GlDispatchCompute
        _glDispatchCompute;
    GlDispatchComputeIndirect
        _glDispatchComputeIndirect;
    GlCopyImageSubData
        _glCopyImageSubData;
    GlFramebufferParameteri
        _glFramebufferParameteri;
    GlGetFramebufferParameteriv
        _glGetFramebufferParameteriv;
    GlGetInternalformati64v
        _glGetInternalformati64v;
    GlInvalidateTexSubImage
        _glInvalidateTexSubImage;
    GlInvalidateTexImage
        _glInvalidateTexImage;
    GlInvalidateBufferSubData
        _glInvalidateBufferSubData;
    GlInvalidateBufferData
        _glInvalidateBufferData;
    GlInvalidateFramebuffer
        _glInvalidateFramebuffer;
    GlInvalidateSubFramebuffer
        _glInvalidateSubFramebuffer;
    GlMultiDrawArraysIndirect
        _glMultiDrawArraysIndirect;
    GlMultiDrawElementsIndirect
        _glMultiDrawElementsIndirect;
    GlGetProgramInterfaceiv
        _glGetProgramInterfaceiv;
    GlGetProgramResourceIndex
        _glGetProgramResourceIndex;
    GlGetProgramResourceName
        _glGetProgramResourceName;
    GlGetProgramResourceiv
        _glGetProgramResourceiv;
    GlGetProgramResourceLocation
        _glGetProgramResourceLocation;
    GlGetProgramResourceLocationIndex
        _glGetProgramResourceLocationIndex;
    GlShaderStorageBlockBinding
        _glShaderStorageBlockBinding;
    GlTexBufferRange
        _glTexBufferRange;
    GlTexStorage2DMultisample
        _glTexStorage2DMultisample;
    GlTexStorage3DMultisample
        _glTexStorage3DMultisample;
    GlTextureView
        _glTextureView;
    GlBindVertexBuffer
        _glBindVertexBuffer;
    GlVertexAttribFormat
        _glVertexAttribFormat;
    GlVertexAttribIFormat
        _glVertexAttribIFormat;
    GlVertexAttribLFormat
        _glVertexAttribLFormat;
    GlVertexAttribBinding
        _glVertexAttribBinding;
    GlVertexBindingDivisor
        _glVertexBindingDivisor;
    GlDebugMessageControl
        _glDebugMessageControl;
    GlDebugMessageInsert
        _glDebugMessageInsert;
    GlDebugMessageCallback
        _glDebugMessageCallback;
    GlGetDebugMessageLog
        _glGetDebugMessageLog;
    GlPushDebugGroup
        _glPushDebugGroup;
    GlPopDebugGroup
        _glPopDebugGroup;
    GlObjectLabel
        _glObjectLabel;
    GlGetObjectLabel
        _glGetObjectLabel;
    GlObjectPtrLabel
        _glObjectPtrLabel;
    GlGetObjectPtrLabel
        _glGetObjectPtrLabel;
    GlBufferStorage
        _glBufferStorage;
    GlClearTexImage
        _glClearTexImage;
    GlClearTexSubImage
        _glClearTexSubImage;
    GlBindBuffersBase
        _glBindBuffersBase;
    GlBindBuffersRange
        _glBindBuffersRange;
    GlBindTextures
        _glBindTextures;
    GlBindSamplers
        _glBindSamplers;
    GlBindImageTextures
        _glBindImageTextures;
    GlBindVertexBuffers
        _glBindVertexBuffers;
    GlClipControl
        _glClipControl;
    GlCreateTransformFeedbacks
        _glCreateTransformFeedbacks;
    GlTransformFeedbackBufferBase
        _glTransformFeedbackBufferBase;
    GlTransformFeedbackBufferRange
        _glTransformFeedbackBufferRange;
    GlGetTransformFeedbackiv
        _glGetTransformFeedbackiv;
    GlGetTransformFeedbacki_v
        _glGetTransformFeedbacki_v;
    GlGetTransformFeedbacki64_v
        _glGetTransformFeedbacki64_v;
    GlCreateBuffers
        _glCreateBuffers;
    GlNamedBufferStorage
        _glNamedBufferStorage;
    GlNamedBufferData
        _glNamedBufferData;
    GlNamedBufferSubData
        _glNamedBufferSubData;
    GlCopyNamedBufferSubData
        _glCopyNamedBufferSubData;
    GlClearNamedBufferData
        _glClearNamedBufferData;
    GlClearNamedBufferSubData
        _glClearNamedBufferSubData;
    GlMapNamedBuffer
        _glMapNamedBuffer;
    GlMapNamedBufferRange
        _glMapNamedBufferRange;
    GlUnmapNamedBuffer
        _glUnmapNamedBuffer;
    GlFlushMappedNamedBufferRange
        _glFlushMappedNamedBufferRange;
    GlGetNamedBufferParameteriv
        _glGetNamedBufferParameteriv;
    GlGetNamedBufferParameteri64v
        _glGetNamedBufferParameteri64v;
    GlGetNamedBufferPointerv
        _glGetNamedBufferPointerv;
    GlGetNamedBufferSubData
        _glGetNamedBufferSubData;
    GlCreateFramebuffers
        _glCreateFramebuffers;
    GlNamedFramebufferRenderbuffer
        _glNamedFramebufferRenderbuffer;
    GlNamedFramebufferParameteri
        _glNamedFramebufferParameteri;
    GlNamedFramebufferTexture
        _glNamedFramebufferTexture;
    GlNamedFramebufferTextureLayer
        _glNamedFramebufferTextureLayer;
    GlNamedFramebufferDrawBuffer
        _glNamedFramebufferDrawBuffer;
    GlNamedFramebufferDrawBuffers
        _glNamedFramebufferDrawBuffers;
    GlNamedFramebufferReadBuffer
        _glNamedFramebufferReadBuffer;
    GlInvalidateNamedFramebufferData
        _glInvalidateNamedFramebufferData;
    GlInvalidateNamedFramebufferSubData
        _glInvalidateNamedFramebufferSubData;
    GlClearNamedFramebufferiv
        _glClearNamedFramebufferiv;
    GlClearNamedFramebufferuiv
        _glClearNamedFramebufferuiv;
    GlClearNamedFramebufferfv
        _glClearNamedFramebufferfv;
    GlClearNamedFramebufferfi
        _glClearNamedFramebufferfi;
    GlBlitNamedFramebuffer
        _glBlitNamedFramebuffer;
    GlCheckNamedFramebufferStatus
        _glCheckNamedFramebufferStatus;
    GlGetNamedFramebufferParameteriv
        _glGetNamedFramebufferParameteriv;
    GlGetNamedFramebufferAttachmentParameteriv
        _glGetNamedFramebufferAttachmentParameteriv;
    GlCreateRenderbuffers
        _glCreateRenderbuffers;
    GlNamedRenderbufferStorage
        _glNamedRenderbufferStorage;
    GlNamedRenderbufferStorageMultisample
        _glNamedRenderbufferStorageMultisample;
    GlGetNamedRenderbufferParameteriv
        _glGetNamedRenderbufferParameteriv;
    GlCreateTextures
        _glCreateTextures;
    GlTextureBuffer
        _glTextureBuffer;
    GlTextureBufferRange
        _glTextureBufferRange;
    GlTextureStorage1D
        _glTextureStorage1D;
    GlTextureStorage2D
        _glTextureStorage2D;
    GlTextureStorage3D
        _glTextureStorage3D;
    GlTextureStorage2DMultisample
        _glTextureStorage2DMultisample;
    GlTextureStorage3DMultisample
        _glTextureStorage3DMultisample;
    GlTextureSubImage1D
        _glTextureSubImage1D;
    GlTextureSubImage2D
        _glTextureSubImage2D;
    GlTextureSubImage3D
        _glTextureSubImage3D;
    GlCompressedTextureSubImage1D
        _glCompressedTextureSubImage1D;
    GlCompressedTextureSubImage2D
        _glCompressedTextureSubImage2D;
    GlCompressedTextureSubImage3D
        _glCompressedTextureSubImage3D;
    GlCopyTextureSubImage1D
        _glCopyTextureSubImage1D;
    GlCopyTextureSubImage2D
        _glCopyTextureSubImage2D;
    GlCopyTextureSubImage3D
        _glCopyTextureSubImage3D;
    GlTextureParameterf
        _glTextureParameterf;
    GlTextureParameterfv
        _glTextureParameterfv;
    GlTextureParameteri
        _glTextureParameteri;
    GlTextureParameterIiv
        _glTextureParameterIiv;
    GlTextureParameterIuiv
        _glTextureParameterIuiv;
    GlTextureParameteriv
        _glTextureParameteriv;
    GlGenerateTextureMipmap
        _glGenerateTextureMipmap;
    GlBindTextureUnit
        _glBindTextureUnit;
    GlGetTextureImage
        _glGetTextureImage;
    GlGetCompressedTextureImage
        _glGetCompressedTextureImage;
    GlGetTextureLevelParameterfv
        _glGetTextureLevelParameterfv;
    GlGetTextureLevelParameteriv
        _glGetTextureLevelParameteriv;
    GlGetTextureParameterfv
        _glGetTextureParameterfv;
    GlGetTextureParameterIiv
        _glGetTextureParameterIiv;
    GlGetTextureParameterIuiv
        _glGetTextureParameterIuiv;
    GlGetTextureParameteriv
        _glGetTextureParameteriv;
    GlCreateVertexArrays
        _glCreateVertexArrays;
    GlDisableVertexArrayAttrib
        _glDisableVertexArrayAttrib;
    GlEnableVertexArrayAttrib
        _glEnableVertexArrayAttrib;
    GlVertexArrayElementBuffer
        _glVertexArrayElementBuffer;
    GlVertexArrayVertexBuffer
        _glVertexArrayVertexBuffer;
    GlVertexArrayVertexBuffers
        _glVertexArrayVertexBuffers;
    GlVertexArrayAttribBinding
        _glVertexArrayAttribBinding;
    GlVertexArrayAttribFormat
        _glVertexArrayAttribFormat;
    GlVertexArrayAttribIFormat
        _glVertexArrayAttribIFormat;
    GlVertexArrayAttribLFormat
        _glVertexArrayAttribLFormat;
    GlVertexArrayBindingDivisor
        _glVertexArrayBindingDivisor;
    GlGetVertexArrayiv
        _glGetVertexArrayiv;
    GlGetVertexArrayIndexediv
        _glGetVertexArrayIndexediv;
    GlGetVertexArrayIndexed64iv
        _glGetVertexArrayIndexed64iv;
    GlCreateSamplers
        _glCreateSamplers;
    GlCreateProgramPipelines
        _glCreateProgramPipelines;
    GlCreateQueries
        _glCreateQueries;
    GlGetQueryBufferObjecti64v
        _glGetQueryBufferObjecti64v;
    GlGetQueryBufferObjectiv
        _glGetQueryBufferObjectiv;
    GlGetQueryBufferObjectui64v
        _glGetQueryBufferObjectui64v;
    GlGetQueryBufferObjectuiv
        _glGetQueryBufferObjectuiv;
    GlMemoryBarrierByRegion
        _glMemoryBarrierByRegion;
    GlGetTextureSubImage
        _glGetTextureSubImage;
    GlGetCompressedTextureSubImage
        _glGetCompressedTextureSubImage;
    GlGetGraphicsResetStatus
        _glGetGraphicsResetStatus;
    GlGetnCompressedTexImage
        _glGetnCompressedTexImage;
    GlGetnTexImage
        _glGetnTexImage;
    GlGetnUniformdv
        _glGetnUniformdv;
    GlGetnUniformfv
        _glGetnUniformfv;
    GlGetnUniformiv
        _glGetnUniformiv;
    GlGetnUniformuiv
        _glGetnUniformuiv;
    GlReadnPixels
        _glReadnPixels;
    GlTextureBarrier
        _glTextureBarrier;
    GlSpecializeShader
        _glSpecializeShader;
    GlMultiDrawArraysIndirectCount
        _glMultiDrawArraysIndirectCount;
    GlMultiDrawElementsIndirectCount
        _glMultiDrawElementsIndirectCount;
    GlPolygonOffsetClamp
        _glPolygonOffsetClamp;
    GlPrimitiveBoundingBoxARB
        _glPrimitiveBoundingBoxARB;
    GlGetTextureHandleARB
        _glGetTextureHandleARB;
    GlGetTextureSamplerHandleARB
        _glGetTextureSamplerHandleARB;
    GlMakeTextureHandleResidentARB
        _glMakeTextureHandleResidentARB;
    GlMakeTextureHandleNonResidentARB
        _glMakeTextureHandleNonResidentARB;
    GlGetImageHandleARB
        _glGetImageHandleARB;
    GlMakeImageHandleResidentARB
        _glMakeImageHandleResidentARB;
    GlMakeImageHandleNonResidentARB
        _glMakeImageHandleNonResidentARB;
    GlUniformHandleui64ARB
        _glUniformHandleui64ARB;
    GlUniformHandleui64vARB
        _glUniformHandleui64vARB;
    GlProgramUniformHandleui64ARB
        _glProgramUniformHandleui64ARB;
    GlProgramUniformHandleui64vARB
        _glProgramUniformHandleui64vARB;
    GlIsTextureHandleResidentARB
        _glIsTextureHandleResidentARB;
    GlIsImageHandleResidentARB
        _glIsImageHandleResidentARB;
    GlVertexAttribL1ui64ARB
        _glVertexAttribL1ui64ARB;
    GlVertexAttribL1ui64vARB
        _glVertexAttribL1ui64vARB;
    GlGetVertexAttribLui64vARB
        _glGetVertexAttribLui64vARB;
    GlCreateSyncFromCLeventARB
        _glCreateSyncFromCLeventARB;
    GlDispatchComputeGroupSizeARB
        _glDispatchComputeGroupSizeARB;
    GlDebugMessageControlARB
        _glDebugMessageControlARB;
    GlDebugMessageInsertARB
        _glDebugMessageInsertARB;
    GlDebugMessageCallbackARB
        _glDebugMessageCallbackARB;
    GlGetDebugMessageLogARB
        _glGetDebugMessageLogARB;
    GlBlendEquationiARB
        _glBlendEquationiARB;
    GlBlendEquationSeparateiARB
        _glBlendEquationSeparateiARB;
    GlBlendFunciARB
        _glBlendFunciARB;
    GlBlendFuncSeparateiARB
        _glBlendFuncSeparateiARB;
    GlDrawArraysInstancedARB
        _glDrawArraysInstancedARB;
    GlDrawElementsInstancedARB
        _glDrawElementsInstancedARB;
    GlProgramParameteriARB
        _glProgramParameteriARB;
    GlFramebufferTextureARB
        _glFramebufferTextureARB;
    GlFramebufferTextureLayerARB
        _glFramebufferTextureLayerARB;
    GlFramebufferTextureFaceARB
        _glFramebufferTextureFaceARB;
    GlSpecializeShaderARB
        _glSpecializeShaderARB;
    GlUniform1i64ARB
        _glUniform1i64ARB;
    GlUniform2i64ARB
        _glUniform2i64ARB;
    GlUniform3i64ARB
        _glUniform3i64ARB;
    GlUniform4i64ARB
        _glUniform4i64ARB;
    GlUniform1i64vARB
        _glUniform1i64vARB;
    GlUniform2i64vARB
        _glUniform2i64vARB;
    GlUniform3i64vARB
        _glUniform3i64vARB;
    GlUniform4i64vARB
        _glUniform4i64vARB;
    GlUniform1ui64ARB
        _glUniform1ui64ARB;
    GlUniform2ui64ARB
        _glUniform2ui64ARB;
    GlUniform3ui64ARB
        _glUniform3ui64ARB;
    GlUniform4ui64ARB
        _glUniform4ui64ARB;
    GlUniform1ui64vARB
        _glUniform1ui64vARB;
    GlUniform2ui64vARB
        _glUniform2ui64vARB;
    GlUniform3ui64vARB
        _glUniform3ui64vARB;
    GlUniform4ui64vARB
        _glUniform4ui64vARB;
    GlGetUniformi64vARB
        _glGetUniformi64vARB;
    GlGetUniformui64vARB
        _glGetUniformui64vARB;
    GlGetnUniformi64vARB
        _glGetnUniformi64vARB;
    GlGetnUniformui64vARB
        _glGetnUniformui64vARB;
    GlProgramUniform1i64ARB
        _glProgramUniform1i64ARB;
    GlProgramUniform2i64ARB
        _glProgramUniform2i64ARB;
    GlProgramUniform3i64ARB
        _glProgramUniform3i64ARB;
    GlProgramUniform4i64ARB
        _glProgramUniform4i64ARB;
    GlProgramUniform1i64vARB
        _glProgramUniform1i64vARB;
    GlProgramUniform2i64vARB
        _glProgramUniform2i64vARB;
    GlProgramUniform3i64vARB
        _glProgramUniform3i64vARB;
    GlProgramUniform4i64vARB
        _glProgramUniform4i64vARB;
    GlProgramUniform1ui64ARB
        _glProgramUniform1ui64ARB;
    GlProgramUniform2ui64ARB
        _glProgramUniform2ui64ARB;
    GlProgramUniform3ui64ARB
        _glProgramUniform3ui64ARB;
    GlProgramUniform4ui64ARB
        _glProgramUniform4ui64ARB;
    GlProgramUniform1ui64vARB
        _glProgramUniform1ui64vARB;
    GlProgramUniform2ui64vARB
        _glProgramUniform2ui64vARB;
    GlProgramUniform3ui64vARB
        _glProgramUniform3ui64vARB;
    GlProgramUniform4ui64vARB
        _glProgramUniform4ui64vARB;
    GlMultiDrawArraysIndirectCountARB
        _glMultiDrawArraysIndirectCountARB;
    GlMultiDrawElementsIndirectCountARB
        _glMultiDrawElementsIndirectCountARB;
    GlVertexAttribDivisorARB
        _glVertexAttribDivisorARB;
    GlMaxShaderCompilerThreadsARB
        _glMaxShaderCompilerThreadsARB;
    GlGetGraphicsResetStatusARB
        _glGetGraphicsResetStatusARB;
    GlGetnTexImageARB
        _glGetnTexImageARB;
    GlReadnPixelsARB
        _glReadnPixelsARB;
    GlGetnCompressedTexImageARB
        _glGetnCompressedTexImageARB;
    GlGetnUniformfvARB
        _glGetnUniformfvARB;
    GlGetnUniformivARB
        _glGetnUniformivARB;
    GlGetnUniformuivARB
        _glGetnUniformuivARB;
    GlGetnUniformdvARB
        _glGetnUniformdvARB;
    GlFramebufferSampleLocationsfvARB
        _glFramebufferSampleLocationsfvARB;
    GlNamedFramebufferSampleLocationsfvARB
        _glNamedFramebufferSampleLocationsfvARB;
    GlEvaluateDepthValuesARB
        _glEvaluateDepthValuesARB;
    GlMinSampleShadingARB
        _glMinSampleShadingARB;
    GlNamedStringARB
        _glNamedStringARB;
    GlDeleteNamedStringARB
        _glDeleteNamedStringARB;
    GlCompileShaderIncludeARB
        _glCompileShaderIncludeARB;
    GlIsNamedStringARB
        _glIsNamedStringARB;
    GlGetNamedStringARB
        _glGetNamedStringARB;
    GlGetNamedStringivARB
        _glGetNamedStringivARB;
    GlBufferPageCommitmentARB
        _glBufferPageCommitmentARB;
    GlNamedBufferPageCommitmentEXT
        _glNamedBufferPageCommitmentEXT;
    GlNamedBufferPageCommitmentARB
        _glNamedBufferPageCommitmentARB;
    GlTexPageCommitmentARB
        _glTexPageCommitmentARB;
    GlTexBufferARB
        _glTexBufferARB;
    GlBlendBarrierKHR
        _glBlendBarrierKHR;
    GlMaxShaderCompilerThreadsKHR
        _glMaxShaderCompilerThreadsKHR;
    GlGetPerfMonitorGroupsAMD
        _glGetPerfMonitorGroupsAMD;
    GlGetPerfMonitorCountersAMD
        _glGetPerfMonitorCountersAMD;
    GlGetPerfMonitorGroupStringAMD
        _glGetPerfMonitorGroupStringAMD;
    GlGetPerfMonitorCounterStringAMD
        _glGetPerfMonitorCounterStringAMD;
    GlGetPerfMonitorCounterInfoAMD
        _glGetPerfMonitorCounterInfoAMD;
    GlGenPerfMonitorsAMD
        _glGenPerfMonitorsAMD;
    GlDeletePerfMonitorsAMD
        _glDeletePerfMonitorsAMD;
    GlSelectPerfMonitorCountersAMD
        _glSelectPerfMonitorCountersAMD;
    GlBeginPerfMonitorAMD
        _glBeginPerfMonitorAMD;
    GlEndPerfMonitorAMD
        _glEndPerfMonitorAMD;
    GlGetPerfMonitorCounterDataAMD
        _glGetPerfMonitorCounterDataAMD;
    GlEGLImageTargetTexStorageEXT
        _glEGLImageTargetTexStorageEXT;
    GlEGLImageTargetTextureStorageEXT
        _glEGLImageTargetTextureStorageEXT;
    GlLabelObjectEXT
        _glLabelObjectEXT;
    GlGetObjectLabelEXT
        _glGetObjectLabelEXT;
    GlInsertEventMarkerEXT
        _glInsertEventMarkerEXT;
    GlPushGroupMarkerEXT
        _glPushGroupMarkerEXT;
    GlPopGroupMarkerEXT
        _glPopGroupMarkerEXT;
    GlMatrixLoadfEXT
        _glMatrixLoadfEXT;
    GlMatrixLoaddEXT
        _glMatrixLoaddEXT;
    GlMatrixMultfEXT
        _glMatrixMultfEXT;
    GlMatrixMultdEXT
        _glMatrixMultdEXT;
    GlMatrixLoadIdentityEXT
        _glMatrixLoadIdentityEXT;
    GlMatrixRotatefEXT
        _glMatrixRotatefEXT;
    GlMatrixRotatedEXT
        _glMatrixRotatedEXT;
    GlMatrixScalefEXT
        _glMatrixScalefEXT;
    GlMatrixScaledEXT
        _glMatrixScaledEXT;
    GlMatrixTranslatefEXT
        _glMatrixTranslatefEXT;
    GlMatrixTranslatedEXT
        _glMatrixTranslatedEXT;
    GlMatrixFrustumEXT
        _glMatrixFrustumEXT;
    GlMatrixOrthoEXT
        _glMatrixOrthoEXT;
    GlMatrixPopEXT
        _glMatrixPopEXT;
    GlMatrixPushEXT
        _glMatrixPushEXT;
    GlClientAttribDefaultEXT
        _glClientAttribDefaultEXT;
    GlPushClientAttribDefaultEXT
        _glPushClientAttribDefaultEXT;
    GlTextureParameterfEXT
        _glTextureParameterfEXT;
    GlTextureParameterfvEXT
        _glTextureParameterfvEXT;
    GlTextureParameteriEXT
        _glTextureParameteriEXT;
    GlTextureParameterivEXT
        _glTextureParameterivEXT;
    GlTextureImage1DEXT
        _glTextureImage1DEXT;
    GlTextureImage2DEXT
        _glTextureImage2DEXT;
    GlTextureSubImage1DEXT
        _glTextureSubImage1DEXT;
    GlTextureSubImage2DEXT
        _glTextureSubImage2DEXT;
    GlCopyTextureImage1DEXT
        _glCopyTextureImage1DEXT;
    GlCopyTextureImage2DEXT
        _glCopyTextureImage2DEXT;
    GlCopyTextureSubImage1DEXT
        _glCopyTextureSubImage1DEXT;
    GlCopyTextureSubImage2DEXT
        _glCopyTextureSubImage2DEXT;
    GlGetTextureImageEXT
        _glGetTextureImageEXT;
    GlGetTextureParameterfvEXT
        _glGetTextureParameterfvEXT;
    GlGetTextureParameterivEXT
        _glGetTextureParameterivEXT;
    GlGetTextureLevelParameterfvEXT
        _glGetTextureLevelParameterfvEXT;
    GlGetTextureLevelParameterivEXT
        _glGetTextureLevelParameterivEXT;
    GlTextureImage3DEXT
        _glTextureImage3DEXT;
    GlTextureSubImage3DEXT
        _glTextureSubImage3DEXT;
    GlCopyTextureSubImage3DEXT
        _glCopyTextureSubImage3DEXT;
    GlBindMultiTextureEXT
        _glBindMultiTextureEXT;
    GlMultiTexCoordPointerEXT
        _glMultiTexCoordPointerEXT;
    GlMultiTexEnvfEXT
        _glMultiTexEnvfEXT;
    GlMultiTexEnvfvEXT
        _glMultiTexEnvfvEXT;
    GlMultiTexEnviEXT
        _glMultiTexEnviEXT;
    GlMultiTexEnvivEXT
        _glMultiTexEnvivEXT;
    GlMultiTexGendEXT
        _glMultiTexGendEXT;
    GlMultiTexGendvEXT
        _glMultiTexGendvEXT;
    GlMultiTexGenfEXT
        _glMultiTexGenfEXT;
    GlMultiTexGenfvEXT
        _glMultiTexGenfvEXT;
    GlMultiTexGeniEXT
        _glMultiTexGeniEXT;
    GlMultiTexGenivEXT
        _glMultiTexGenivEXT;
    GlGetMultiTexEnvfvEXT
        _glGetMultiTexEnvfvEXT;
    GlGetMultiTexEnvivEXT
        _glGetMultiTexEnvivEXT;
    GlGetMultiTexGendvEXT
        _glGetMultiTexGendvEXT;
    GlGetMultiTexGenfvEXT
        _glGetMultiTexGenfvEXT;
    GlGetMultiTexGenivEXT
        _glGetMultiTexGenivEXT;
    GlMultiTexParameteriEXT
        _glMultiTexParameteriEXT;
    GlMultiTexParameterivEXT
        _glMultiTexParameterivEXT;
    GlMultiTexParameterfEXT
        _glMultiTexParameterfEXT;
    GlMultiTexParameterfvEXT
        _glMultiTexParameterfvEXT;
    GlMultiTexImage1DEXT
        _glMultiTexImage1DEXT;
    GlMultiTexImage2DEXT
        _glMultiTexImage2DEXT;
    GlMultiTexSubImage1DEXT
        _glMultiTexSubImage1DEXT;
    GlMultiTexSubImage2DEXT
        _glMultiTexSubImage2DEXT;
    GlCopyMultiTexImage1DEXT
        _glCopyMultiTexImage1DEXT;
    GlCopyMultiTexImage2DEXT
        _glCopyMultiTexImage2DEXT;
    GlCopyMultiTexSubImage1DEXT
        _glCopyMultiTexSubImage1DEXT;
    GlCopyMultiTexSubImage2DEXT
        _glCopyMultiTexSubImage2DEXT;
    GlGetMultiTexImageEXT
        _glGetMultiTexImageEXT;
    GlGetMultiTexParameterfvEXT
        _glGetMultiTexParameterfvEXT;
    GlGetMultiTexParameterivEXT
        _glGetMultiTexParameterivEXT;
    GlGetMultiTexLevelParameterfvEXT
        _glGetMultiTexLevelParameterfvEXT;
    GlGetMultiTexLevelParameterivEXT
        _glGetMultiTexLevelParameterivEXT;
    GlMultiTexImage3DEXT
        _glMultiTexImage3DEXT;
    GlMultiTexSubImage3DEXT
        _glMultiTexSubImage3DEXT;
    GlCopyMultiTexSubImage3DEXT
        _glCopyMultiTexSubImage3DEXT;
    GlEnableClientStateIndexedEXT
        _glEnableClientStateIndexedEXT;
    GlDisableClientStateIndexedEXT
        _glDisableClientStateIndexedEXT;
    GlGetFloatIndexedvEXT
        _glGetFloatIndexedvEXT;
    GlGetDoubleIndexedvEXT
        _glGetDoubleIndexedvEXT;
    GlGetPointerIndexedvEXT
        _glGetPointerIndexedvEXT;
    GlEnableIndexedEXT
        _glEnableIndexedEXT;
    GlDisableIndexedEXT
        _glDisableIndexedEXT;
    GlIsEnabledIndexedEXT
        _glIsEnabledIndexedEXT;
    GlGetIntegerIndexedvEXT
        _glGetIntegerIndexedvEXT;
    GlGetBooleanIndexedvEXT
        _glGetBooleanIndexedvEXT;
    GlCompressedTextureImage3DEXT
        _glCompressedTextureImage3DEXT;
    GlCompressedTextureImage2DEXT
        _glCompressedTextureImage2DEXT;
    GlCompressedTextureImage1DEXT
        _glCompressedTextureImage1DEXT;
    GlCompressedTextureSubImage3DEXT
        _glCompressedTextureSubImage3DEXT;
    GlCompressedTextureSubImage2DEXT
        _glCompressedTextureSubImage2DEXT;
    GlCompressedTextureSubImage1DEXT
        _glCompressedTextureSubImage1DEXT;
    GlGetCompressedTextureImageEXT
        _glGetCompressedTextureImageEXT;
    GlCompressedMultiTexImage3DEXT
        _glCompressedMultiTexImage3DEXT;
    GlCompressedMultiTexImage2DEXT
        _glCompressedMultiTexImage2DEXT;
    GlCompressedMultiTexImage1DEXT
        _glCompressedMultiTexImage1DEXT;
    GlCompressedMultiTexSubImage3DEXT
        _glCompressedMultiTexSubImage3DEXT;
    GlCompressedMultiTexSubImage2DEXT
        _glCompressedMultiTexSubImage2DEXT;
    GlCompressedMultiTexSubImage1DEXT
        _glCompressedMultiTexSubImage1DEXT;
    GlGetCompressedMultiTexImageEXT
        _glGetCompressedMultiTexImageEXT;
    GlMatrixLoadTransposefEXT
        _glMatrixLoadTransposefEXT;
    GlMatrixLoadTransposedEXT
        _glMatrixLoadTransposedEXT;
    GlMatrixMultTransposefEXT
        _glMatrixMultTransposefEXT;
    GlMatrixMultTransposedEXT
        _glMatrixMultTransposedEXT;
    GlNamedBufferDataEXT
        _glNamedBufferDataEXT;
    GlNamedBufferSubDataEXT
        _glNamedBufferSubDataEXT;
    GlMapNamedBufferEXT
        _glMapNamedBufferEXT;
    GlUnmapNamedBufferEXT
        _glUnmapNamedBufferEXT;
    GlGetNamedBufferParameterivEXT
        _glGetNamedBufferParameterivEXT;
    GlGetNamedBufferPointervEXT
        _glGetNamedBufferPointervEXT;
    GlGetNamedBufferSubDataEXT
        _glGetNamedBufferSubDataEXT;
    GlProgramUniform1fEXT
        _glProgramUniform1fEXT;
    GlProgramUniform2fEXT
        _glProgramUniform2fEXT;
    GlProgramUniform3fEXT
        _glProgramUniform3fEXT;
    GlProgramUniform4fEXT
        _glProgramUniform4fEXT;
    GlProgramUniform1iEXT
        _glProgramUniform1iEXT;
    GlProgramUniform2iEXT
        _glProgramUniform2iEXT;
    GlProgramUniform3iEXT
        _glProgramUniform3iEXT;
    GlProgramUniform4iEXT
        _glProgramUniform4iEXT;
    GlProgramUniform1fvEXT
        _glProgramUniform1fvEXT;
    GlProgramUniform2fvEXT
        _glProgramUniform2fvEXT;
    GlProgramUniform3fvEXT
        _glProgramUniform3fvEXT;
    GlProgramUniform4fvEXT
        _glProgramUniform4fvEXT;
    GlProgramUniform1ivEXT
        _glProgramUniform1ivEXT;
    GlProgramUniform2ivEXT
        _glProgramUniform2ivEXT;
    GlProgramUniform3ivEXT
        _glProgramUniform3ivEXT;
    GlProgramUniform4ivEXT
        _glProgramUniform4ivEXT;
    GlProgramUniformMatrix2fvEXT
        _glProgramUniformMatrix2fvEXT;
    GlProgramUniformMatrix3fvEXT
        _glProgramUniformMatrix3fvEXT;
    GlProgramUniformMatrix4fvEXT
        _glProgramUniformMatrix4fvEXT;
    GlProgramUniformMatrix2x3fvEXT
        _glProgramUniformMatrix2x3fvEXT;
    GlProgramUniformMatrix3x2fvEXT
        _glProgramUniformMatrix3x2fvEXT;
    GlProgramUniformMatrix2x4fvEXT
        _glProgramUniformMatrix2x4fvEXT;
    GlProgramUniformMatrix4x2fvEXT
        _glProgramUniformMatrix4x2fvEXT;
    GlProgramUniformMatrix3x4fvEXT
        _glProgramUniformMatrix3x4fvEXT;
    GlProgramUniformMatrix4x3fvEXT
        _glProgramUniformMatrix4x3fvEXT;
    GlTextureBufferEXT
        _glTextureBufferEXT;
    GlMultiTexBufferEXT
        _glMultiTexBufferEXT;
    GlTextureParameterIivEXT
        _glTextureParameterIivEXT;
    GlTextureParameterIuivEXT
        _glTextureParameterIuivEXT;
    GlGetTextureParameterIivEXT
        _glGetTextureParameterIivEXT;
    GlGetTextureParameterIuivEXT
        _glGetTextureParameterIuivEXT;
    GlMultiTexParameterIivEXT
        _glMultiTexParameterIivEXT;
    GlMultiTexParameterIuivEXT
        _glMultiTexParameterIuivEXT;
    GlGetMultiTexParameterIivEXT
        _glGetMultiTexParameterIivEXT;
    GlGetMultiTexParameterIuivEXT
        _glGetMultiTexParameterIuivEXT;
    GlProgramUniform1uiEXT
        _glProgramUniform1uiEXT;
    GlProgramUniform2uiEXT
        _glProgramUniform2uiEXT;
    GlProgramUniform3uiEXT
        _glProgramUniform3uiEXT;
    GlProgramUniform4uiEXT
        _glProgramUniform4uiEXT;
    GlProgramUniform1uivEXT
        _glProgramUniform1uivEXT;
    GlProgramUniform2uivEXT
        _glProgramUniform2uivEXT;
    GlProgramUniform3uivEXT
        _glProgramUniform3uivEXT;
    GlProgramUniform4uivEXT
        _glProgramUniform4uivEXT;
    GlNamedProgramLocalParameters4fvEXT
        _glNamedProgramLocalParameters4fvEXT;
    GlNamedProgramLocalParameterI4iEXT
        _glNamedProgramLocalParameterI4iEXT;
    GlNamedProgramLocalParameterI4ivEXT
        _glNamedProgramLocalParameterI4ivEXT;
    GlNamedProgramLocalParametersI4ivEXT
        _glNamedProgramLocalParametersI4ivEXT;
    GlNamedProgramLocalParameterI4uiEXT
        _glNamedProgramLocalParameterI4uiEXT;
    GlNamedProgramLocalParameterI4uivEXT
        _glNamedProgramLocalParameterI4uivEXT;
    GlNamedProgramLocalParametersI4uivEXT
        _glNamedProgramLocalParametersI4uivEXT;
    GlGetNamedProgramLocalParameterIivEXT
        _glGetNamedProgramLocalParameterIivEXT;
    GlGetNamedProgramLocalParameterIuivEXT
        _glGetNamedProgramLocalParameterIuivEXT;
    GlEnableClientStateiEXT
        _glEnableClientStateiEXT;
    GlDisableClientStateiEXT
        _glDisableClientStateiEXT;
    GlGetFloati_vEXT
        _glGetFloati_vEXT;
    GlGetDoublei_vEXT
        _glGetDoublei_vEXT;
    GlGetPointeri_vEXT
        _glGetPointeri_vEXT;
    GlNamedProgramStringEXT
        _glNamedProgramStringEXT;
    GlNamedProgramLocalParameter4dEXT
        _glNamedProgramLocalParameter4dEXT;
    GlNamedProgramLocalParameter4dvEXT
        _glNamedProgramLocalParameter4dvEXT;
    GlNamedProgramLocalParameter4fEXT
        _glNamedProgramLocalParameter4fEXT;
    GlNamedProgramLocalParameter4fvEXT
        _glNamedProgramLocalParameter4fvEXT;
    GlGetNamedProgramLocalParameterdvEXT
        _glGetNamedProgramLocalParameterdvEXT;
    GlGetNamedProgramLocalParameterfvEXT
        _glGetNamedProgramLocalParameterfvEXT;
    GlGetNamedProgramivEXT
        _glGetNamedProgramivEXT;
    GlGetNamedProgramStringEXT
        _glGetNamedProgramStringEXT;
    GlNamedRenderbufferStorageEXT
        _glNamedRenderbufferStorageEXT;
    GlGetNamedRenderbufferParameterivEXT
        _glGetNamedRenderbufferParameterivEXT;
    GlNamedRenderbufferStorageMultisampleEXT
        _glNamedRenderbufferStorageMultisampleEXT;
    GlNamedRenderbufferStorageMultisampleCoverageEXT
        _glNamedRenderbufferStorageMultisampleCoverageEXT;
    GlCheckNamedFramebufferStatusEXT
        _glCheckNamedFramebufferStatusEXT;
    GlNamedFramebufferTexture1DEXT
        _glNamedFramebufferTexture1DEXT;
    GlNamedFramebufferTexture2DEXT
        _glNamedFramebufferTexture2DEXT;
    GlNamedFramebufferTexture3DEXT
        _glNamedFramebufferTexture3DEXT;
    GlNamedFramebufferRenderbufferEXT
        _glNamedFramebufferRenderbufferEXT;
    GlGetNamedFramebufferAttachmentParameterivEXT
        _glGetNamedFramebufferAttachmentParameterivEXT;
    GlGenerateTextureMipmapEXT
        _glGenerateTextureMipmapEXT;
    GlGenerateMultiTexMipmapEXT
        _glGenerateMultiTexMipmapEXT;
    GlFramebufferDrawBufferEXT
        _glFramebufferDrawBufferEXT;
    GlFramebufferDrawBuffersEXT
        _glFramebufferDrawBuffersEXT;
    GlFramebufferReadBufferEXT
        _glFramebufferReadBufferEXT;
    GlGetFramebufferParameterivEXT
        _glGetFramebufferParameterivEXT;
    GlNamedCopyBufferSubDataEXT
        _glNamedCopyBufferSubDataEXT;
    GlNamedFramebufferTextureEXT
        _glNamedFramebufferTextureEXT;
    GlNamedFramebufferTextureLayerEXT
        _glNamedFramebufferTextureLayerEXT;
    GlNamedFramebufferTextureFaceEXT
        _glNamedFramebufferTextureFaceEXT;
    GlTextureRenderbufferEXT
        _glTextureRenderbufferEXT;
    GlMultiTexRenderbufferEXT
        _glMultiTexRenderbufferEXT;
    GlVertexArrayVertexOffsetEXT
        _glVertexArrayVertexOffsetEXT;
    GlVertexArrayColorOffsetEXT
        _glVertexArrayColorOffsetEXT;
    GlVertexArrayEdgeFlagOffsetEXT
        _glVertexArrayEdgeFlagOffsetEXT;
    GlVertexArrayIndexOffsetEXT
        _glVertexArrayIndexOffsetEXT;
    GlVertexArrayNormalOffsetEXT
        _glVertexArrayNormalOffsetEXT;
    GlVertexArrayTexCoordOffsetEXT
        _glVertexArrayTexCoordOffsetEXT;
    GlVertexArrayMultiTexCoordOffsetEXT
        _glVertexArrayMultiTexCoordOffsetEXT;
    GlVertexArrayFogCoordOffsetEXT
        _glVertexArrayFogCoordOffsetEXT;
    GlVertexArraySecondaryColorOffsetEXT
        _glVertexArraySecondaryColorOffsetEXT;
    GlVertexArrayVertexAttribOffsetEXT
        _glVertexArrayVertexAttribOffsetEXT;
    GlVertexArrayVertexAttribIOffsetEXT
        _glVertexArrayVertexAttribIOffsetEXT;
    GlEnableVertexArrayEXT
        _glEnableVertexArrayEXT;
    GlDisableVertexArrayEXT
        _glDisableVertexArrayEXT;
    GlEnableVertexArrayAttribEXT
        _glEnableVertexArrayAttribEXT;
    GlDisableVertexArrayAttribEXT
        _glDisableVertexArrayAttribEXT;
    GlGetVertexArrayIntegervEXT
        _glGetVertexArrayIntegervEXT;
    GlGetVertexArrayPointervEXT
        _glGetVertexArrayPointervEXT;
    GlGetVertexArrayIntegeri_vEXT
        _glGetVertexArrayIntegeri_vEXT;
    GlGetVertexArrayPointeri_vEXT
        _glGetVertexArrayPointeri_vEXT;
    GlMapNamedBufferRangeEXT
        _glMapNamedBufferRangeEXT;
    GlFlushMappedNamedBufferRangeEXT
        _glFlushMappedNamedBufferRangeEXT;
    GlNamedBufferStorageEXT
        _glNamedBufferStorageEXT;
    GlClearNamedBufferDataEXT
        _glClearNamedBufferDataEXT;
    GlClearNamedBufferSubDataEXT
        _glClearNamedBufferSubDataEXT;
    GlNamedFramebufferParameteriEXT
        _glNamedFramebufferParameteriEXT;
    GlGetNamedFramebufferParameterivEXT
        _glGetNamedFramebufferParameterivEXT;
    GlProgramUniform1dEXT
        _glProgramUniform1dEXT;
    GlProgramUniform2dEXT
        _glProgramUniform2dEXT;
    GlProgramUniform3dEXT
        _glProgramUniform3dEXT;
    GlProgramUniform4dEXT
        _glProgramUniform4dEXT;
    GlProgramUniform1dvEXT
        _glProgramUniform1dvEXT;
    GlProgramUniform2dvEXT
        _glProgramUniform2dvEXT;
    GlProgramUniform3dvEXT
        _glProgramUniform3dvEXT;
    GlProgramUniform4dvEXT
        _glProgramUniform4dvEXT;
    GlProgramUniformMatrix2dvEXT
        _glProgramUniformMatrix2dvEXT;
    GlProgramUniformMatrix3dvEXT
        _glProgramUniformMatrix3dvEXT;
    GlProgramUniformMatrix4dvEXT
        _glProgramUniformMatrix4dvEXT;
    GlProgramUniformMatrix2x3dvEXT
        _glProgramUniformMatrix2x3dvEXT;
    GlProgramUniformMatrix2x4dvEXT
        _glProgramUniformMatrix2x4dvEXT;
    GlProgramUniformMatrix3x2dvEXT
        _glProgramUniformMatrix3x2dvEXT;
    GlProgramUniformMatrix3x4dvEXT
        _glProgramUniformMatrix3x4dvEXT;
    GlProgramUniformMatrix4x2dvEXT
        _glProgramUniformMatrix4x2dvEXT;
    GlProgramUniformMatrix4x3dvEXT
        _glProgramUniformMatrix4x3dvEXT;
    GlTextureBufferRangeEXT
        _glTextureBufferRangeEXT;
    GlTextureStorage1DEXT
        _glTextureStorage1DEXT;
    GlTextureStorage2DEXT
        _glTextureStorage2DEXT;
    GlTextureStorage3DEXT
        _glTextureStorage3DEXT;
    GlTextureStorage2DMultisampleEXT
        _glTextureStorage2DMultisampleEXT;
    GlTextureStorage3DMultisampleEXT
        _glTextureStorage3DMultisampleEXT;
    GlVertexArrayBindVertexBufferEXT
        _glVertexArrayBindVertexBufferEXT;
    GlVertexArrayVertexAttribFormatEXT
        _glVertexArrayVertexAttribFormatEXT;
    GlVertexArrayVertexAttribIFormatEXT
        _glVertexArrayVertexAttribIFormatEXT;
    GlVertexArrayVertexAttribLFormatEXT
        _glVertexArrayVertexAttribLFormatEXT;
    GlVertexArrayVertexAttribBindingEXT
        _glVertexArrayVertexAttribBindingEXT;
    GlVertexArrayVertexBindingDivisorEXT
        _glVertexArrayVertexBindingDivisorEXT;
    GlVertexArrayVertexAttribLOffsetEXT
        _glVertexArrayVertexAttribLOffsetEXT;
    GlTexturePageCommitmentEXT
        _glTexturePageCommitmentEXT;
    GlVertexArrayVertexAttribDivisorEXT
        _glVertexArrayVertexAttribDivisorEXT;
    GlDrawArraysInstancedEXT
        _glDrawArraysInstancedEXT;
    GlDrawElementsInstancedEXT
        _glDrawElementsInstancedEXT;
    GlPolygonOffsetClampEXT
        _glPolygonOffsetClampEXT;
    GlRasterSamplesEXT
        _glRasterSamplesEXT;
    GlUseShaderProgramEXT
        _glUseShaderProgramEXT;
    GlActiveProgramEXT
        _glActiveProgramEXT;
    GlCreateShaderProgramEXT
        _glCreateShaderProgramEXT;
    GlFramebufferFetchBarrierEXT
        _glFramebufferFetchBarrierEXT;
    GlWindowRectanglesEXT
        _glWindowRectanglesEXT;
    GlApplyFramebufferAttachmentCMAAINTEL
        _glApplyFramebufferAttachmentCMAAINTEL;
    GlBeginPerfQueryINTEL
        _glBeginPerfQueryINTEL;
    GlCreatePerfQueryINTEL
        _glCreatePerfQueryINTEL;
    GlDeletePerfQueryINTEL
        _glDeletePerfQueryINTEL;
    GlEndPerfQueryINTEL
        _glEndPerfQueryINTEL;
    GlGetFirstPerfQueryIdINTEL
        _glGetFirstPerfQueryIdINTEL;
    GlGetNextPerfQueryIdINTEL
        _glGetNextPerfQueryIdINTEL;
    GlGetPerfCounterInfoINTEL
        _glGetPerfCounterInfoINTEL;
    GlGetPerfQueryDataINTEL
        _glGetPerfQueryDataINTEL;
    GlGetPerfQueryIdByNameINTEL
        _glGetPerfQueryIdByNameINTEL;
    GlGetPerfQueryInfoINTEL
        _glGetPerfQueryInfoINTEL;
    GlMultiDrawArraysIndirectBindlessNV
        _glMultiDrawArraysIndirectBindlessNV;
    GlMultiDrawElementsIndirectBindlessNV
        _glMultiDrawElementsIndirectBindlessNV;
    GlMultiDrawArraysIndirectBindlessCountNV
        _glMultiDrawArraysIndirectBindlessCountNV;
    GlMultiDrawElementsIndirectBindlessCountNV
        _glMultiDrawElementsIndirectBindlessCountNV;
    GlGetTextureHandleNV
        _glGetTextureHandleNV;
    GlGetTextureSamplerHandleNV
        _glGetTextureSamplerHandleNV;
    GlMakeTextureHandleResidentNV
        _glMakeTextureHandleResidentNV;
    GlMakeTextureHandleNonResidentNV
        _glMakeTextureHandleNonResidentNV;
    GlGetImageHandleNV
        _glGetImageHandleNV;
    GlMakeImageHandleResidentNV
        _glMakeImageHandleResidentNV;
    GlMakeImageHandleNonResidentNV
        _glMakeImageHandleNonResidentNV;
    GlUniformHandleui64NV
        _glUniformHandleui64NV;
    GlUniformHandleui64vNV
        _glUniformHandleui64vNV;
    GlProgramUniformHandleui64NV
        _glProgramUniformHandleui64NV;
    GlProgramUniformHandleui64vNV
        _glProgramUniformHandleui64vNV;
    GlIsTextureHandleResidentNV
        _glIsTextureHandleResidentNV;
    GlIsImageHandleResidentNV
        _glIsImageHandleResidentNV;
    GlBlendParameteriNV
        _glBlendParameteriNV;
    GlBlendBarrierNV
        _glBlendBarrierNV;
    GlViewportPositionWScaleNV
        _glViewportPositionWScaleNV;
    GlCreateStatesNV
        _glCreateStatesNV;
    GlDeleteStatesNV
        _glDeleteStatesNV;
    GlIsStateNV
        _glIsStateNV;
    GlStateCaptureNV
        _glStateCaptureNV;
    GlGetCommandHeaderNV
        _glGetCommandHeaderNV;
    GlGetStageIndexNV
        _glGetStageIndexNV;
    GlDrawCommandsNV
        _glDrawCommandsNV;
    GlDrawCommandsAddressNV
        _glDrawCommandsAddressNV;
    GlDrawCommandsStatesNV
        _glDrawCommandsStatesNV;
    GlDrawCommandsStatesAddressNV
        _glDrawCommandsStatesAddressNV;
    GlCreateCommandListsNV
        _glCreateCommandListsNV;
    GlDeleteCommandListsNV
        _glDeleteCommandListsNV;
    GlIsCommandListNV
        _glIsCommandListNV;
    GlListDrawCommandsStatesClientNV
        _glListDrawCommandsStatesClientNV;
    GlCommandListSegmentsNV
        _glCommandListSegmentsNV;
    GlCompileCommandListNV
        _glCompileCommandListNV;
    GlCallCommandListNV
        _glCallCommandListNV;
    GlBeginConditionalRenderNV
        _glBeginConditionalRenderNV;
    GlEndConditionalRenderNV
        _glEndConditionalRenderNV;
    GlSubpixelPrecisionBiasNV
        _glSubpixelPrecisionBiasNV;
    GlConservativeRasterParameterfNV
        _glConservativeRasterParameterfNV;
    GlConservativeRasterParameteriNV
        _glConservativeRasterParameteriNV;
    GlDrawVkImageNV
        _glDrawVkImageNV;
    GlGetVkProcAddrNV
        _glGetVkProcAddrNV;
    GlWaitVkSemaphoreNV
        _glWaitVkSemaphoreNV;
    GlSignalVkSemaphoreNV
        _glSignalVkSemaphoreNV;
    GlSignalVkFenceNV
        _glSignalVkFenceNV;
    GlFragmentCoverageColorNV
        _glFragmentCoverageColorNV;
    GlCoverageModulationTableNV
        _glCoverageModulationTableNV;
    GlGetCoverageModulationTableNV
        _glGetCoverageModulationTableNV;
    GlCoverageModulationNV
        _glCoverageModulationNV;
    GlRenderbufferStorageMultisampleCoverageNV
        _glRenderbufferStorageMultisampleCoverageNV;
    GlUniform1i64NV
        _glUniform1i64NV;
    GlUniform2i64NV
        _glUniform2i64NV;
    GlUniform3i64NV
        _glUniform3i64NV;
    GlUniform4i64NV
        _glUniform4i64NV;
    GlUniform1i64vNV
        _glUniform1i64vNV;
    GlUniform2i64vNV
        _glUniform2i64vNV;
    GlUniform3i64vNV
        _glUniform3i64vNV;
    GlUniform4i64vNV
        _glUniform4i64vNV;
    GlUniform1ui64NV
        _glUniform1ui64NV;
    GlUniform2ui64NV
        _glUniform2ui64NV;
    GlUniform3ui64NV
        _glUniform3ui64NV;
    GlUniform4ui64NV
        _glUniform4ui64NV;
    GlUniform1ui64vNV
        _glUniform1ui64vNV;
    GlUniform2ui64vNV
        _glUniform2ui64vNV;
    GlUniform3ui64vNV
        _glUniform3ui64vNV;
    GlUniform4ui64vNV
        _glUniform4ui64vNV;
    GlGetUniformi64vNV
        _glGetUniformi64vNV;
    GlProgramUniform1i64NV
        _glProgramUniform1i64NV;
    GlProgramUniform2i64NV
        _glProgramUniform2i64NV;
    GlProgramUniform3i64NV
        _glProgramUniform3i64NV;
    GlProgramUniform4i64NV
        _glProgramUniform4i64NV;
    GlProgramUniform1i64vNV
        _glProgramUniform1i64vNV;
    GlProgramUniform2i64vNV
        _glProgramUniform2i64vNV;
    GlProgramUniform3i64vNV
        _glProgramUniform3i64vNV;
    GlProgramUniform4i64vNV
        _glProgramUniform4i64vNV;
    GlProgramUniform1ui64NV
        _glProgramUniform1ui64NV;
    GlProgramUniform2ui64NV
        _glProgramUniform2ui64NV;
    GlProgramUniform3ui64NV
        _glProgramUniform3ui64NV;
    GlProgramUniform4ui64NV
        _glProgramUniform4ui64NV;
    GlProgramUniform1ui64vNV
        _glProgramUniform1ui64vNV;
    GlProgramUniform2ui64vNV
        _glProgramUniform2ui64vNV;
    GlProgramUniform3ui64vNV
        _glProgramUniform3ui64vNV;
    GlProgramUniform4ui64vNV
        _glProgramUniform4ui64vNV;
    GlGetInternalformatSampleivNV
        _glGetInternalformatSampleivNV;
    GlGenPathsNV
        _glGenPathsNV;
    GlDeletePathsNV
        _glDeletePathsNV;
    GlIsPathNV
        _glIsPathNV;
    GlPathCommandsNV
        _glPathCommandsNV;
    GlPathCoordsNV
        _glPathCoordsNV;
    GlPathSubCommandsNV
        _glPathSubCommandsNV;
    GlPathSubCoordsNV
        _glPathSubCoordsNV;
    GlPathStringNV
        _glPathStringNV;
    GlPathGlyphsNV
        _glPathGlyphsNV;
    GlPathGlyphRangeNV
        _glPathGlyphRangeNV;
    GlWeightPathsNV
        _glWeightPathsNV;
    GlCopyPathNV
        _glCopyPathNV;
    GlInterpolatePathsNV
        _glInterpolatePathsNV;
    GlTransformPathNV
        _glTransformPathNV;
    GlPathParameterivNV
        _glPathParameterivNV;
    GlPathParameteriNV
        _glPathParameteriNV;
    GlPathParameterfvNV
        _glPathParameterfvNV;
    GlPathParameterfNV
        _glPathParameterfNV;
    GlPathDashArrayNV
        _glPathDashArrayNV;
    GlPathStencilFuncNV
        _glPathStencilFuncNV;
    GlPathStencilDepthOffsetNV
        _glPathStencilDepthOffsetNV;
    GlStencilFillPathNV
        _glStencilFillPathNV;
    GlStencilStrokePathNV
        _glStencilStrokePathNV;
    GlStencilFillPathInstancedNV
        _glStencilFillPathInstancedNV;
    GlStencilStrokePathInstancedNV
        _glStencilStrokePathInstancedNV;
    GlPathCoverDepthFuncNV
        _glPathCoverDepthFuncNV;
    GlCoverFillPathNV
        _glCoverFillPathNV;
    GlCoverStrokePathNV
        _glCoverStrokePathNV;
    GlCoverFillPathInstancedNV
        _glCoverFillPathInstancedNV;
    GlCoverStrokePathInstancedNV
        _glCoverStrokePathInstancedNV;
    GlGetPathParameterivNV
        _glGetPathParameterivNV;
    GlGetPathParameterfvNV
        _glGetPathParameterfvNV;
    GlGetPathCommandsNV
        _glGetPathCommandsNV;
    GlGetPathCoordsNV
        _glGetPathCoordsNV;
    GlGetPathDashArrayNV
        _glGetPathDashArrayNV;
    GlGetPathMetricsNV
        _glGetPathMetricsNV;
    GlGetPathMetricRangeNV
        _glGetPathMetricRangeNV;
    GlGetPathSpacingNV
        _glGetPathSpacingNV;
    GlIsPointInFillPathNV
        _glIsPointInFillPathNV;
    GlIsPointInStrokePathNV
        _glIsPointInStrokePathNV;
    GlGetPathLengthNV
        _glGetPathLengthNV;
    GlPointAlongPathNV
        _glPointAlongPathNV;
    GlMatrixLoad3x2fNV
        _glMatrixLoad3x2fNV;
    GlMatrixLoad3x3fNV
        _glMatrixLoad3x3fNV;
    GlMatrixLoadTranspose3x3fNV
        _glMatrixLoadTranspose3x3fNV;
    GlMatrixMult3x2fNV
        _glMatrixMult3x2fNV;
    GlMatrixMult3x3fNV
        _glMatrixMult3x3fNV;
    GlMatrixMultTranspose3x3fNV
        _glMatrixMultTranspose3x3fNV;
    GlStencilThenCoverFillPathNV
        _glStencilThenCoverFillPathNV;
    GlStencilThenCoverStrokePathNV
        _glStencilThenCoverStrokePathNV;
    GlStencilThenCoverFillPathInstancedNV
        _glStencilThenCoverFillPathInstancedNV;
    GlStencilThenCoverStrokePathInstancedNV
        _glStencilThenCoverStrokePathInstancedNV;
    GlPathGlyphIndexRangeNV
        _glPathGlyphIndexRangeNV;
    GlPathGlyphIndexArrayNV
        _glPathGlyphIndexArrayNV;
    GlPathMemoryGlyphIndexArrayNV
        _glPathMemoryGlyphIndexArrayNV;
    GlProgramPathFragmentInputGenNV
        _glProgramPathFragmentInputGenNV;
    GlGetProgramResourcefvNV
        _glGetProgramResourcefvNV;
    GlFramebufferSampleLocationsfvNV
        _glFramebufferSampleLocationsfvNV;
    GlNamedFramebufferSampleLocationsfvNV
        _glNamedFramebufferSampleLocationsfvNV;
    GlResolveDepthValuesNV
        _glResolveDepthValuesNV;
    GlMakeBufferResidentNV
        _glMakeBufferResidentNV;
    GlMakeBufferNonResidentNV
        _glMakeBufferNonResidentNV;
    GlIsBufferResidentNV
        _glIsBufferResidentNV;
    GlMakeNamedBufferResidentNV
        _glMakeNamedBufferResidentNV;
    GlMakeNamedBufferNonResidentNV
        _glMakeNamedBufferNonResidentNV;
    GlIsNamedBufferResidentNV
        _glIsNamedBufferResidentNV;
    GlGetBufferParameterui64vNV
        _glGetBufferParameterui64vNV;
    GlGetNamedBufferParameterui64vNV
        _glGetNamedBufferParameterui64vNV;
    GlGetIntegerui64vNV
        _glGetIntegerui64vNV;
    GlUniformui64NV
        _glUniformui64NV;
    GlUniformui64vNV
        _glUniformui64vNV;
    GlGetUniformui64vNV
        _glGetUniformui64vNV;
    GlProgramUniformui64NV
        _glProgramUniformui64NV;
    GlProgramUniformui64vNV
        _glProgramUniformui64vNV;
    GlTextureBarrierNV
        _glTextureBarrierNV;
    GlVertexAttribL1i64NV
        _glVertexAttribL1i64NV;
    GlVertexAttribL2i64NV
        _glVertexAttribL2i64NV;
    GlVertexAttribL3i64NV
        _glVertexAttribL3i64NV;
    GlVertexAttribL4i64NV
        _glVertexAttribL4i64NV;
    GlVertexAttribL1i64vNV
        _glVertexAttribL1i64vNV;
    GlVertexAttribL2i64vNV
        _glVertexAttribL2i64vNV;
    GlVertexAttribL3i64vNV
        _glVertexAttribL3i64vNV;
    GlVertexAttribL4i64vNV
        _glVertexAttribL4i64vNV;
    GlVertexAttribL1ui64NV
        _glVertexAttribL1ui64NV;
    GlVertexAttribL2ui64NV
        _glVertexAttribL2ui64NV;
    GlVertexAttribL3ui64NV
        _glVertexAttribL3ui64NV;
    GlVertexAttribL4ui64NV
        _glVertexAttribL4ui64NV;
    GlVertexAttribL1ui64vNV
        _glVertexAttribL1ui64vNV;
    GlVertexAttribL2ui64vNV
        _glVertexAttribL2ui64vNV;
    GlVertexAttribL3ui64vNV
        _glVertexAttribL3ui64vNV;
    GlVertexAttribL4ui64vNV
        _glVertexAttribL4ui64vNV;
    GlGetVertexAttribLi64vNV
        _glGetVertexAttribLi64vNV;
    GlGetVertexAttribLui64vNV
        _glGetVertexAttribLui64vNV;
    GlVertexAttribLFormatNV
        _glVertexAttribLFormatNV;
    GlBufferAddressRangeNV
        _glBufferAddressRangeNV;
    GlVertexFormatNV
        _glVertexFormatNV;
    GlNormalFormatNV
        _glNormalFormatNV;
    GlColorFormatNV
        _glColorFormatNV;
    GlIndexFormatNV
        _glIndexFormatNV;
    GlTexCoordFormatNV
        _glTexCoordFormatNV;
    GlEdgeFlagFormatNV
        _glEdgeFlagFormatNV;
    GlSecondaryColorFormatNV
        _glSecondaryColorFormatNV;
    GlFogCoordFormatNV
        _glFogCoordFormatNV;
    GlVertexAttribFormatNV
        _glVertexAttribFormatNV;
    GlVertexAttribIFormatNV
        _glVertexAttribIFormatNV;
    GlGetIntegerui64i_vNV
        _glGetIntegerui64i_vNV;
    GlViewportSwizzleNV
        _glViewportSwizzleNV;
    GlFramebufferTextureMultiviewOVR
        _glFramebufferTextureMultiviewOVR;

#ifdef _WIN32
    WglGetExtensionsStringEXT
        _wglGetExtensionsStringEXT;
    WglGetExtensionsStringARB
        _wglGetExtensionsStringARB;
    WglCreateContextAttribsARB
        _wglCreateContextAttribsARB;
    WglSwapIntervalEXT
        _wglSwapIntervalEXT;
#endif

#ifdef __linux__
    GlXCreateContextAttribsARB
        _glXCreateContextAttribsARB;
    GlXSwapIntervalEXT
        _glXSwapIntervalEXT;
    GlXSwapIntervalMESA
        _glXSwapIntervalMESA;
#endif
};

}

#include <storm/ogl/gpu_context_ogl.inl>
