#include <storm/input.h>

namespace storm {

std::string_view getKeyboardKeyName( KeyboardKey key ) {
    const char *names[] = {
        "Escape",
        "F1",
        "F2",
        "F3",
        "F4",
        "F5",
        "F6",
        "F7",
        "F8",
        "F9",
        "F10",
        "F11",
        "F12",
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
        "~",
        "-",
        "=",
        "[",
        "]",
        ";",
        ",",
        ".",
        "/",
        "\\",
        "'",
        "Enter",
        "Space",
        "Tab",
        "Backspace",
        "Delete",
        "Insert",
        "Left",
        "Right",
        "Up",
        "Down",
        "Home",
        "End",
        "Page Up",
        "Page Down",
        "L. Shift",
        "R. Shift",
        "L. Control",
        "R. Control",
        "L. Alter",
        "R. Alter",
        "Num Lock",
        "Num 0",
        "Num 1",
        "Num 2",
        "Num 3",
        "Num 4",
        "Num 5",
        "Num 6",
        "Num 7",
        "Num 8",
        "Num 9",
        "Num /",
        "Num *",
        "Num -",
        "Num +",
        "Num Enter",
        "Num Delete",
        "Caps Lock",
        "Scroll Lock",
        "Print Screen",
        "Pause",
        "L. Command",
        "R. Command",
        "Menu"
    };

    const size_t index = static_cast<size_t>( key );

    if( index < std::size(names) ) {
        return names[index];
    } else {
        return "";
    }
}

}
